In [139]:
import numpy as np

# reshape 차원을 바꿈
arr = [1, 2, 3, 4]
a = np.array(arr)
print(a)
b = a.reshape(2, 2)
print(b)
print(b.reshape(4))





[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]


In [20]:
a = np.array([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]])

print(a[1:2][0][1])

4


In [23]:
a = np.array([[0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]])

In [39]:
a[[2, 1]].reshape(6)

array([6, 7, 8, 3, 4, 5])

In [42]:
a[[0, 1]]

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
a[ : : 2] # 2차원 슬라이싱


array([[0, 1, 2],
       [6, 7, 8]])

In [59]:
a[ : , 0] # 행을 다 슬라이싱하고 열 0번째

array([0, 3, 6])

In [84]:
a[1:3, 1:2] # 2차원 선택

array([[4],
       [7]])

In [97]:
a[:, [0, 1]]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [111]:
a = np.array([[30, 25, 66],
             [23, 44, 23]])
sum(a[1])
print(a.mean(axis=1))

[40.33333333 30.        ]


In [116]:
영어 = a[:, 1]
print(sum(영어)/len(영어))

34.5


In [140]:
a = np.array([30, 25, 66, 23, 44, 23]).reshape(2, 3)
영어 = a[:, 1]
print(sum(영어)/len(영어))

34.5


AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [130]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
    ])

b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3, 3)

print(f'{a}\n\n {b}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 4 5]
 [6 7 8]]
